services:
  backend:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: spam-detector-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: spam-detector-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
      WATCHPACK_POLLING: "true"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - /app/.git
    depends_on:
      - backend
    command: sh -c "npm install && npm run dev"
